# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service/stock/stock_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service/stock/stock_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!service/stock/stock_service.proto\x12\x1bservice.stock.stock_service\"T\n\x0cStockRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x1e\n\x11\x61nnual_report_url\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x14\n\x12_annual_report_url\"\xb3\x03\n\rStockResponse\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\t\x12\x1a\n\rcurrent_price\x18\x04 \x01(\x01H\x00\x88\x01\x01\x12\x15\n\rtotal_revenue\x18\x05 \x01(\x01\x12\x19\n\x11operating_revenue\x18\x06 \x01(\x01\x12\x18\n\x10operating_income\x18\x07 \x01(\x01\x12\x12\n\nnet_income\x18\x08 \x01(\x01\x12\x13\n\x06\x65\x62itda\x18\t \x01(\x01H\x01\x88\x01\x01\x12\x10\n\x03\x65ps\x18\n \x01(\x01H\x02\x88\x01\x01\x12!\n\x14\x62\x61sic_average_shares\x18\x0b \x01(\x01H\x03\x88\x01\x01\x12%\n\x18research_and_development\x18\x0c \x01(\x01H\x04\x88\x01\x01\x12\x1b\n\x0etotal_expenses\x18\r \x01(\x01H\x05\x88\x01\x01\x42\x10\n\x0e_current_priceB\t\n\x07_ebitdaB\x06\n\x04_epsB\x17\n\x15_basic_average_sharesB\x1b\n\x19_research_and_developmentB\x11\n\x0f_total_expenses2u\n\x0cStockService\x12\x65\n\x0cGetStockInfo\x12).service.stock.stock_service.StockRequest\x1a*.service.stock.stock_service.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service.stock.stock_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=66
  _globals['_STOCKREQUEST']._serialized_end=150
  _globals['_STOCKRESPONSE']._serialized_start=153
  _globals['_STOCKRESPONSE']._serialized_end=588
  _globals['_STOCKSERVICE']._serialized_start=590
  _globals['_STOCKSERVICE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
